#!/bin/sh

echo "test"

forbidden_branches='main'
current_branch=$(git branch --show-current)

for branch in $forbidden_branches; do
    if [ "$branch" = "$current_branch" ]; then
        echo "❌ Direct commits to main branch are forbidden"
        exit 1
    fi
done

echo "🔍 Starting type-check"
npm run type-check
if [ $? -ne 0 ]; then
    echo "❌Type errors were found"
    exit 1
fi
